// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function left(v) {
  return {
    TAG: "Left",
    _0: v
  };
}

function right(v) {
  return {
    TAG: "Right",
    _0: v
  };
}

function is_left(x) {
  return x.TAG === "Left";
}

function is_right(x) {
  return x.TAG !== "Left";
}

function find_left(x) {
  if (x.TAG === "Left") {
    return Primitive_option.some(x._0);
  }
  
}

function find_right(x) {
  if (x.TAG === "Left") {
    return;
  } else {
    return Primitive_option.some(x._0);
  }
}

function map_left(f, x) {
  if (x.TAG === "Left") {
    return {
      TAG: "Left",
      _0: f(x._0)
    };
  } else {
    return x;
  }
}

function map_right(f, x) {
  if (x.TAG === "Left") {
    return x;
  } else {
    return {
      TAG: "Right",
      _0: f(x._0)
    };
  }
}

function map(left, right, x) {
  if (x.TAG === "Left") {
    return {
      TAG: "Left",
      _0: left(x._0)
    };
  } else {
    return {
      TAG: "Right",
      _0: right(x._0)
    };
  }
}

function fold(left, right, x) {
  if (x.TAG === "Left") {
    return left(x._0);
  } else {
    return right(x._0);
  }
}

function equal(left, right, e1, e2) {
  if (e1.TAG === "Left") {
    if (e2.TAG === "Left") {
      return left(e1._0, e2._0);
    } else {
      return false;
    }
  } else if (e2.TAG === "Left") {
    return false;
  } else {
    return right(e1._0, e2._0);
  }
}

function compare(left, right, e1, e2) {
  if (e1.TAG === "Left") {
    if (e2.TAG === "Left") {
      return left(e1._0, e2._0);
    } else {
      return -1;
    }
  } else if (e2.TAG === "Left") {
    return 1;
  } else {
    return right(e1._0, e2._0);
  }
}

let iter = fold;

let for_all = fold;

export {
  left,
  right,
  is_left,
  is_right,
  find_left,
  find_right,
  map_left,
  map_right,
  map,
  fold,
  iter,
  for_all,
  equal,
  compare,
}
/* No side effect */
