// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lazy from "rescript/lib/es6/Lazy.js";
import * as Pervasives from "rescript/lib/es6/Pervasives.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "rescript/lib/es6/Primitive_exceptions.js";

function empty() {
  return "Nil";
}

function $$return(x) {
  return {
    TAG: "Cons",
    _0: x,
    _1: empty
  };
}

function cons(x, next, param) {
  return {
    TAG: "Cons",
    _0: x,
    _1: next
  };
}

function append(seq1, seq2, param) {
  let match = seq1();
  if (typeof match !== "object") {
    return seq2();
  }
  let next = match._1;
  return {
    TAG: "Cons",
    _0: match._0,
    _1: __x => append(next, seq2, __x)
  };
}

function map(f, seq, param) {
  let match = seq();
  if (typeof match !== "object") {
    return "Nil";
  }
  let next = match._1;
  return {
    TAG: "Cons",
    _0: f(match._0),
    _1: __x => map(f, next, __x)
  };
}

function filter_map(f, _seq, _param) {
  while (true) {
    let seq = _seq;
    let match = seq();
    if (typeof match !== "object") {
      return "Nil";
    }
    let next = match._1;
    let y = f(match._0);
    if (y !== undefined) {
      return {
        TAG: "Cons",
        _0: Primitive_option.valFromOption(y),
        _1: __x => filter_map(f, next, __x)
      };
    }
    _param = undefined;
    _seq = next;
    continue;
  };
}

function filter(f, _seq, _param) {
  while (true) {
    let seq = _seq;
    let match = seq();
    if (typeof match !== "object") {
      return "Nil";
    }
    let next = match._1;
    let x = match._0;
    if (f(x)) {
      return {
        TAG: "Cons",
        _0: x,
        _1: __x => filter(f, next, __x)
      };
    }
    _param = undefined;
    _seq = next;
    continue;
  };
}

function concat(seq, param) {
  let match = seq();
  if (typeof match !== "object") {
    return "Nil";
  }
  let next = match._1;
  return append(match._0, __x => concat(next, __x), undefined);
}

function flat_map(f, seq, param) {
  let match = seq();
  if (typeof match !== "object") {
    return "Nil";
  }
  let next = match._1;
  return append(f(match._0), __x => flat_map(f, next, __x), undefined);
}

function fold_left(f, _acc, _seq) {
  while (true) {
    let seq = _seq;
    let acc = _acc;
    let match = seq();
    if (typeof match !== "object") {
      return acc;
    }
    let acc$1 = f(acc, match._0);
    _seq = match._1;
    _acc = acc$1;
    continue;
  };
}

function iter(f, _seq) {
  while (true) {
    let seq = _seq;
    let match = seq();
    if (typeof match !== "object") {
      return;
    }
    f(match._0);
    _seq = match._1;
    continue;
  };
}

function unfold(f, u, param) {
  let match = f(u);
  if (match === undefined) {
    return "Nil";
  }
  let u$p = match[1];
  return {
    TAG: "Cons",
    _0: match[0],
    _1: __x => unfold(f, u$p, __x)
  };
}

function is_empty(xs) {
  let match = xs();
  return typeof match !== "object";
}

function uncons(xs) {
  let match = xs();
  if (typeof match !== "object") {
    return;
  } else {
    return [
      match._0,
      match._1
    ];
  }
}

function length_aux(_accu, _xs) {
  while (true) {
    let xs = _xs;
    let accu = _accu;
    let match = xs();
    if (typeof match !== "object") {
      return accu;
    }
    _xs = match._1;
    _accu = accu + 1 | 0;
    continue;
  };
}

function length(xs) {
  return length_aux(0, xs);
}

function iteri_aux(f, _i, _xs) {
  while (true) {
    let xs = _xs;
    let i = _i;
    let match = xs();
    if (typeof match !== "object") {
      return;
    }
    f(i, match._0);
    _xs = match._1;
    _i = i + 1 | 0;
    continue;
  };
}

function iteri(f, xs) {
  iteri_aux(f, 0, xs);
}

function fold_lefti_aux(f, _accu, _i, _xs) {
  while (true) {
    let xs = _xs;
    let i = _i;
    let accu = _accu;
    let match = xs();
    if (typeof match !== "object") {
      return accu;
    }
    let accu$1 = f(accu, i, match._0);
    _xs = match._1;
    _i = i + 1 | 0;
    _accu = accu$1;
    continue;
  };
}

function fold_lefti(f, accu, xs) {
  return fold_lefti_aux(f, accu, 0, xs);
}

function for_all(p, _xs) {
  while (true) {
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return true;
    }
    if (!p(match._0)) {
      return false;
    }
    _xs = match._1;
    continue;
  };
}

function exists(p, _xs) {
  while (true) {
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return false;
    }
    if (p(match._0)) {
      return true;
    }
    _xs = match._1;
    continue;
  };
}

function find(p, _xs) {
  while (true) {
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return;
    }
    let x = match._0;
    if (p(x)) {
      return Primitive_option.some(x);
    }
    _xs = match._1;
    continue;
  };
}

function find_map(f, _xs) {
  while (true) {
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return;
    }
    let result = f(match._0);
    if (result !== undefined) {
      return result;
    }
    _xs = match._1;
    continue;
  };
}

function iter2(f, _xs, _ys) {
  while (true) {
    let ys = _ys;
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return;
    }
    let match$1 = ys();
    if (typeof match$1 !== "object") {
      return;
    }
    f(match._0, match$1._0);
    _ys = match$1._1;
    _xs = match._1;
    continue;
  };
}

function fold_left2(f, _accu, _xs, _ys) {
  while (true) {
    let ys = _ys;
    let xs = _xs;
    let accu = _accu;
    let match = xs();
    if (typeof match !== "object") {
      return accu;
    }
    let match$1 = ys();
    if (typeof match$1 !== "object") {
      return accu;
    }
    let accu$1 = f(accu, match._0, match$1._0);
    _ys = match$1._1;
    _xs = match._1;
    _accu = accu$1;
    continue;
  };
}

function for_all2(f, _xs, _ys) {
  while (true) {
    let ys = _ys;
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return true;
    }
    let match$1 = ys();
    if (typeof match$1 !== "object") {
      return true;
    }
    if (!f(match._0, match$1._0)) {
      return false;
    }
    _ys = match$1._1;
    _xs = match._1;
    continue;
  };
}

function exists2(f, _xs, _ys) {
  while (true) {
    let ys = _ys;
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return false;
    }
    let match$1 = ys();
    if (typeof match$1 !== "object") {
      return false;
    }
    if (f(match._0, match$1._0)) {
      return true;
    }
    _ys = match$1._1;
    _xs = match._1;
    continue;
  };
}

function equal(eq, _xs, _ys) {
  while (true) {
    let ys = _ys;
    let xs = _xs;
    let match = xs();
    let match$1 = ys();
    if (typeof match !== "object") {
      return typeof match$1 !== "object";
    }
    if (typeof match$1 !== "object") {
      return false;
    }
    if (!eq(match._0, match$1._0)) {
      return false;
    }
    _ys = match$1._1;
    _xs = match._1;
    continue;
  };
}

function compare(cmp, _xs, _ys) {
  while (true) {
    let ys = _ys;
    let xs = _xs;
    let match = xs();
    let match$1 = ys();
    if (typeof match !== "object") {
      if (typeof match$1 !== "object") {
        return 0;
      } else {
        return -1;
      }
    }
    if (typeof match$1 !== "object") {
      return 1;
    }
    let c = cmp(match._0, match$1._0);
    if (c !== 0) {
      return c;
    }
    _ys = match$1._1;
    _xs = match._1;
    continue;
  };
}

function init_aux(f, i, j, param) {
  if (i < j) {
    return {
      TAG: "Cons",
      _0: f(i),
      _1: __x => init_aux(f, i + 1 | 0, j, __x)
    };
  } else {
    return "Nil";
  }
}

function init(n, f) {
  if (n < 0) {
    return Pervasives.invalid_arg("Seq.init");
  } else {
    return __x => init_aux(f, 0, n, __x);
  }
}

function repeat(x, param) {
  return {
    TAG: "Cons",
    _0: x,
    _1: __x => repeat(x, __x)
  };
}

function forever(f, param) {
  return {
    TAG: "Cons",
    _0: f(),
    _1: __x => forever(f, __x)
  };
}

function cycle_nonempty(xs, param) {
  return append(xs, __x => cycle_nonempty(xs, __x), undefined);
}

function cycle(xs, param) {
  let match = xs();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xs$p = match._1;
  return {
    TAG: "Cons",
    _0: match._0,
    _1: __x => append(xs$p, __x => cycle_nonempty(xs, __x), __x)
  };
}

function iterate1(f, x, param) {
  let y = f(x);
  return {
    TAG: "Cons",
    _0: y,
    _1: __x => iterate1(f, y, __x)
  };
}

function iterate(f, x) {
  return __x => ({
    TAG: "Cons",
    _0: x,
    _1: __x => iterate1(f, x, __x)
  });
}

function mapi_aux(f, i, xs, param) {
  let match = xs();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xs$1 = match._1;
  return {
    TAG: "Cons",
    _0: f(i, match._0),
    _1: __x => mapi_aux(f, i + 1 | 0, xs$1, __x)
  };
}

function mapi(f, xs) {
  return __x => mapi_aux(f, 0, xs, __x);
}

function tail_scan(f, s, xs, param) {
  let match = xs();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xs$1 = match._1;
  let s$1 = f(s, match._0);
  return {
    TAG: "Cons",
    _0: s$1,
    _1: __x => tail_scan(f, s$1, xs$1, __x)
  };
}

function scan(f, s, xs) {
  return __x => ({
    TAG: "Cons",
    _0: s,
    _1: __x => tail_scan(f, s, xs, __x)
  });
}

function take_aux(n, xs) {
  if (n === 0) {
    return empty;
  } else {
    return () => {
      let match = xs();
      if (typeof match !== "object") {
        return "Nil";
      } else {
        return {
          TAG: "Cons",
          _0: match._0,
          _1: take_aux(n - 1 | 0, match._1)
        };
      }
    };
  }
}

function take(n, xs) {
  if (n < 0) {
    Pervasives.invalid_arg("Seq.take");
  }
  return take_aux(n, xs);
}

function force_drop(_n, _xs) {
  while (true) {
    let xs = _xs;
    let n = _n;
    let match = xs();
    if (typeof match !== "object") {
      return "Nil";
    }
    let xs$1 = match._1;
    let n$1 = n - 1 | 0;
    if (n$1 === 0) {
      return xs$1();
    }
    _xs = xs$1;
    _n = n$1;
    continue;
  };
}

function drop(n, xs) {
  if (n < 0) {
    return Pervasives.invalid_arg("Seq.drop");
  } else if (n === 0) {
    return xs;
  } else {
    return () => force_drop(n, xs);
  }
}

function take_while(p, xs, param) {
  let match = xs();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xs$1 = match._1;
  let x = match._0;
  if (p(x)) {
    return {
      TAG: "Cons",
      _0: x,
      _1: __x => take_while(p, xs$1, __x)
    };
  } else {
    return "Nil";
  }
}

function drop_while(p, _xs, _param) {
  while (true) {
    let xs = _xs;
    let node = xs();
    if (typeof node !== "object") {
      return "Nil";
    }
    if (!p(node._0)) {
      return node;
    }
    _param = undefined;
    _xs = node._1;
    continue;
  };
}

function group(eq, xs, param) {
  let match = xs();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xs$1 = match._1;
  let x = match._0;
  return {
    TAG: "Cons",
    _0: __x => ({
      TAG: "Cons",
      _0: x,
      _1: __x => take_while(eq(x), xs$1, __x)
    }),
    _1: __x => group(eq, __x => drop_while(eq(x), xs$1, __x), __x)
  };
}

let Forced_twice = /* @__PURE__ */Primitive_exceptions.create("Seq-Bag.Forced_twice");

function from_lazy(s) {
  return () => Lazy.force(s);
}

function memoize(s) {
  let s$1 = Lazy.from_fun(s);
  return () => Lazy.force(s$1);
}

let Suspension = {
  to_lazy: Lazy.from_fun,
  from_lazy: from_lazy,
  memoize: memoize
};

function memoize$1(xs) {
  let s = Lazy.from_fun(() => {
    let match = xs();
    if (typeof match !== "object") {
      return "Nil";
    } else {
      return {
        TAG: "Cons",
        _0: match._0,
        _1: memoize$1(match._1)
      };
    }
  });
  return () => Lazy.force(s);
}

function zip(xs, ys, param) {
  let match = xs();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xs$1 = match._1;
  let match$1 = ys();
  if (typeof match$1 !== "object") {
    return "Nil";
  }
  let ys$1 = match$1._1;
  return {
    TAG: "Cons",
    _0: [
      match._0,
      match$1._0
    ],
    _1: __x => zip(xs$1, ys$1, __x)
  };
}

function map2(f, xs, ys, param) {
  let match = xs();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xs$1 = match._1;
  let match$1 = ys();
  if (typeof match$1 !== "object") {
    return "Nil";
  }
  let ys$1 = match$1._1;
  return {
    TAG: "Cons",
    _0: f(match._0, match$1._0),
    _1: __x => map2(f, xs$1, ys$1, __x)
  };
}

function interleave(xs, ys, param) {
  let match = xs();
  if (typeof match !== "object") {
    return ys();
  }
  let xs$1 = match._1;
  return {
    TAG: "Cons",
    _0: match._0,
    _1: __x => interleave(ys, xs$1, __x)
  };
}

function sorted_merge1l(cmp, x, xs, ys, param) {
  let match = ys();
  if (typeof match !== "object") {
    return {
      TAG: "Cons",
      _0: x,
      _1: xs
    };
  } else {
    return sorted_merge1(cmp, x, xs, match._0, match._1);
  }
}

function sorted_merge1r(cmp, xs, y, ys, param) {
  let match = xs();
  if (typeof match !== "object") {
    return {
      TAG: "Cons",
      _0: y,
      _1: ys
    };
  } else {
    return sorted_merge1(cmp, match._0, match._1, y, ys);
  }
}

function sorted_merge1(cmp, x, xs, y, ys) {
  if (cmp(x, y) <= 0) {
    return {
      TAG: "Cons",
      _0: x,
      _1: __x => sorted_merge1r(cmp, xs, y, ys, __x)
    };
  } else {
    return {
      TAG: "Cons",
      _0: y,
      _1: __x => sorted_merge1l(cmp, x, xs, ys, __x)
    };
  }
}

function sorted_merge(cmp, xs, ys, param) {
  let match = xs();
  let match$1 = ys();
  if (typeof match !== "object") {
    if (typeof match$1 !== "object") {
      return "Nil";
    } else {
      return match$1;
    }
  } else if (typeof match$1 !== "object") {
    return match;
  } else {
    return sorted_merge1(cmp, match._0, match._1, match$1._0, match$1._1);
  }
}

function map_fst(xys, param) {
  let match = xys();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xys$1 = match._1;
  return {
    TAG: "Cons",
    _0: match._0[0],
    _1: __x => map_fst(xys$1, __x)
  };
}

function map_snd(xys, param) {
  let match = xys();
  if (typeof match !== "object") {
    return "Nil";
  }
  let xys$1 = match._1;
  return {
    TAG: "Cons",
    _0: match._0[1],
    _1: __x => map_snd(xys$1, __x)
  };
}

function unzip(xys) {
  return [
    __x => map_fst(xys, __x),
    __x => map_snd(xys, __x)
  ];
}

function filter_map_find_left_map(f, _xs, _param) {
  while (true) {
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return "Nil";
    }
    let xs$1 = match._1;
    let y = f(match._0);
    if (y.TAG === "Left") {
      return {
        TAG: "Cons",
        _0: y._0,
        _1: __x => filter_map_find_left_map(f, xs$1, __x)
      };
    }
    _param = undefined;
    _xs = xs$1;
    continue;
  };
}

function filter_map_find_right_map(f, _xs, _param) {
  while (true) {
    let xs = _xs;
    let match = xs();
    if (typeof match !== "object") {
      return "Nil";
    }
    let xs$1 = match._1;
    let z = f(match._0);
    if (z.TAG !== "Left") {
      return {
        TAG: "Cons",
        _0: z._0,
        _1: __x => filter_map_find_right_map(f, xs$1, __x)
      };
    }
    _param = undefined;
    _xs = xs$1;
    continue;
  };
}

function partition_map(f, xs) {
  return [
    __x => filter_map_find_left_map(f, xs, __x),
    __x => filter_map_find_right_map(f, xs, __x)
  ];
}

function partition(p, xs) {
  return [
    __x => filter(p, xs, __x),
    __x => filter(x => !p(x), xs, __x)
  ];
}

function peel(xss) {
  return unzip(__x => filter_map(uncons, xss, __x));
}

function transpose(xss, param) {
  let match = peel(xss);
  let tails = match[1];
  let heads = match[0];
  if (!is_empty(heads)) {
    return {
      TAG: "Cons",
      _0: heads,
      _1: __x => transpose(tails, __x)
    };
  }
  if (!is_empty(tails)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "seq.res",
        583,
        4
      ],
      Error: new Error()
    };
  }
  return "Nil";
}

function diagonals(remainders, xss, param) {
  let match = xss();
  if (typeof match !== "object") {
    return transpose(remainders, undefined);
  }
  let xss$1 = match._1;
  let match$1 = match._0();
  if (typeof match$1 !== "object") {
    let match$2 = peel(remainders);
    let tails = match$2[1];
    return {
      TAG: "Cons",
      _0: match$2[0],
      _1: __x => diagonals(tails, xss$1, __x)
    };
  }
  let xs = match$1._1;
  let x = match$1._0;
  let match$3 = peel(remainders);
  let tails$1 = match$3[1];
  let heads = match$3[0];
  return {
    TAG: "Cons",
    _0: __x => ({
      TAG: "Cons",
      _0: x,
      _1: heads
    }),
    _1: __x => diagonals(__x => ({
      TAG: "Cons",
      _0: xs,
      _1: tails$1
    }), xss$1, __x)
  };
}

function diagonals$1(xss) {
  return __x => diagonals(empty, xss, __x);
}

function map_product(f, xs, ys) {
  return __x => concat(diagonals$1(__x => map(x => (__x => map(y => f(x, y), ys, __x)), xs, __x)), __x);
}

function product(xs, ys) {
  return map_product((x, y) => [
    x,
    y
  ], xs, ys);
}

function of_dispenser(it) {
  let c = () => {
    let x = it();
    if (x !== undefined) {
      return {
        TAG: "Cons",
        _0: Primitive_option.valFromOption(x),
        _1: c
      };
    } else {
      return "Nil";
    }
  };
  return c;
}

function to_dispenser(xs) {
  let s = {
    contents: xs
  };
  return () => {
    let match = s.contents();
    if (typeof match !== "object") {
      return;
    }
    s.contents = match._1;
    return Primitive_option.some(match._0);
  };
}

function ints(i, param) {
  return {
    TAG: "Cons",
    _0: i,
    _1: __x => ints(i + 1 | 0, __x)
  };
}

let concat_map = flat_map;

let split = unzip;

export {
  empty,
  $$return,
  cons,
  append,
  map,
  filter_map,
  filter,
  concat,
  flat_map,
  concat_map,
  fold_left,
  iter,
  unfold,
  is_empty,
  uncons,
  length_aux,
  length,
  iteri_aux,
  iteri,
  fold_lefti_aux,
  fold_lefti,
  for_all,
  exists,
  find,
  find_map,
  iter2,
  fold_left2,
  for_all2,
  exists2,
  equal,
  compare,
  init_aux,
  init,
  repeat,
  forever,
  cycle_nonempty,
  cycle,
  iterate1,
  iterate,
  mapi_aux,
  mapi,
  tail_scan,
  scan,
  take_aux,
  take,
  force_drop,
  drop,
  take_while,
  drop_while,
  group,
  Forced_twice,
  Suspension,
  memoize$1 as memoize,
  zip,
  map2,
  interleave,
  sorted_merge1l,
  sorted_merge1r,
  sorted_merge1,
  sorted_merge,
  map_fst,
  map_snd,
  unzip,
  split,
  filter_map_find_left_map,
  filter_map_find_right_map,
  partition_map,
  partition,
  peel,
  transpose,
  diagonals$1 as diagonals,
  map_product,
  product,
  of_dispenser,
  to_dispenser,
  ints,
}
/* No side effect */
