// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Math from "rescript/lib/es6/Math.js";
import * as Bag$Bag from "../src/bag.res.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";

let cmp = Primitive_object.compare;

let I = {
  cmp: cmp
};

let B = Bag$Bag.Make(I);

let a = B.add(1, 1, B.add(2, 2, B.add(3, 3, B.empty)));

let b = B.add(1, 4, B.add(2, 5, B.add(3, 6, B.empty)));

if (B.cardinal(a) !== 6) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      13,
      2
    ],
    Error: new Error()
  };
}

if (B.cardinal(B.sum(a, b)) !== 21) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      14,
      2
    ],
    Error: new Error()
  };
}

if (B.cardinal(B.union(a, b)) !== 15) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      15,
      2
    ],
    Error: new Error()
  };
}

if (!B.is_empty(B.diff(a, b))) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      16,
      2
    ],
    Error: new Error()
  };
}

if (B.cardinal(B.diff(b, a)) !== 9) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      17,
      2
    ],
    Error: new Error()
  };
}

if (!B.equal(B.inter(a, b), a)) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      18,
      2
    ],
    Error: new Error()
  };
}

if (!B.included(a, b)) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      19,
      2
    ],
    Error: new Error()
  };
}

if (B.included(b, a)) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      20,
      2
    ],
    Error: new Error()
  };
}

if (B.disjoint(b, a)) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      21,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(B.elements(a), {
    hd: [
      1,
      1
    ],
    tl: {
      hd: [
        2,
        2
      ],
      tl: {
        hd: [
          3,
          3
        ],
        tl: /* [] */0
      }
    }
  })) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      22,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(B.min_elt(a), [
    1,
    1
  ])) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      23,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(B.max_elt(a), [
    3,
    3
  ])) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      24,
      2
    ],
    Error: new Error()
  };
}

function f(param) {
  return 1;
}

if (B.cardinal(B.map(f, a)) !== 3) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      26,
      2
    ],
    Error: new Error()
  };
}

if (B.cardinal(B.map(f, b)) !== 3) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      27,
      2
    ],
    Error: new Error()
  };
}

let e = B.filter((x, param) => x % 2 === 0, a);

if (!Primitive_object.equal(B.min_elt(e), [
    2,
    2
  ])) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      29,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(B.max_elt(e), [
    2,
    2
  ])) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      30,
      2
    ],
    Error: new Error()
  };
}

if (B.cardinal(e) !== 2) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      32,
      2
    ],
    Error: new Error()
  };
}

let o = B.filter((x, param) => x % 2 === 1, b);

if (!Primitive_object.equal(B.min_elt(o), [
    1,
    4
  ])) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      34,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(B.max_elt(o), [
    3,
    6
  ])) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      35,
      2
    ],
    Error: new Error()
  };
}

if (B.cardinal(o) !== 10) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test.res",
      36,
      2
    ],
    Error: new Error()
  };
}

function test(n) {
  let b1 = B.empty;
  let b2 = B.empty;
  for (let x = 0; x <= n; ++x) {
    b1 = B.add(x, 2, b1);
    if (B.cardinal(b1) !== ((x + 1 | 0) << 1)) {
      throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "test.res",
          45,
          4
        ],
        Error: new Error()
      };
    }
    b2 = B.add(n - x | 0, undefined, b2);
    if (B.cardinal(b2) !== ((x << 1) + 1 | 0)) {
      throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "test.res",
          47,
          4
        ],
        Error: new Error()
      };
    }
    b2 = B.add(n - x | 0, undefined, b2);
    if (x < (n / 2 | 0) && !B.disjoint(b1, b2)) {
      throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "test.res",
          50,
          6
        ],
        Error: new Error()
      };
    }
    
  }
  if (!B.mem(n, b1)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        53,
        2
      ],
      Error: new Error()
    };
  }
  if (B.occ(n, b1) !== 2) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        54,
        2
      ],
      Error: new Error()
    };
  }
  if (B.cardinal(b1) !== ((n + 1 | 0) << 1)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        55,
        2
      ],
      Error: new Error()
    };
  }
  if (B.cardinal(b2) !== ((n + 1 | 0) << 1)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        56,
        2
      ],
      Error: new Error()
    };
  }
  if (!B.equal(b1, b2)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        57,
        2
      ],
      Error: new Error()
    };
  }
  if (!B.for_all((x, param) => x <= n, b1)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        58,
        2
      ],
      Error: new Error()
    };
  }
  if (B.for_all((x, param) => x < n, b1)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        59,
        2
      ],
      Error: new Error()
    };
  }
  if (!B.exists((x, m) => {
      if (x === 0) {
        return m === 2;
      } else {
        return false;
      }
    }, b2)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        60,
        2
      ],
      Error: new Error()
    };
  }
  for (let x$1 = 0; x$1 <= n; ++x$1) {
    b1 = B.remove_all(x$1, b1);
    b2 = B.remove(n - x$1 | 0, 2, b2);
  }
  if (!B.is_empty(b1)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        65,
        2
      ],
      Error: new Error()
    };
  }
  if (!B.is_empty(b2)) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        66,
        2
      ],
      Error: new Error()
    };
  }
  
}

for (let n = 0; n <= 10; ++n) {
  test(Math.imul(10, n));
}

function test$1(n) {
  let b1 = B.empty;
  let b2 = B.empty;
  let random = $$Math.Int.random;
  for (let i = 0; i < n; ++i) {
    b1 = B.add(i, random(1, 10), b1);
    b2 = B.add(i, random(1, 3), b2);
  }
  let match = B.div(b1, b2);
  if (!B.equal(b1, B.sum(B.mul(b2, match[0]), match[1]))) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        87,
        2
      ],
      Error: new Error()
    };
  }
  let match$1 = B.divi(b1, 1);
  if (!(B.equal(match$1[0], b1) && B.is_empty(match$1[1]))) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "test.res",
        89,
        2
      ],
      Error: new Error()
    };
  }
  for (let k = 2; k <= 5; ++k) {
    let match$2 = B.divi(b1, k);
    if (!B.equal(b1, B.sum(B.mul(match$2[0], k), match$2[1]))) {
      throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "test.res",
          92,
          4
        ],
        Error: new Error()
      };
    }
    
  }
}

for (let n$1 = 0; n$1 <= 100; ++n$1) {
  test$1(n$1);
}

export {
  I,
  B,
  test$1 as test,
}
/* B Not a pure module */
