// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Option from "rescript/lib/es6/Option.js";
import * as Belt_Id from "rescript/lib/es6/Belt_Id.js";
import * as Belt_Map from "rescript/lib/es6/Belt_Map.js";
import * as Pervasives from "rescript/lib/es6/Pervasives.js";
import * as Primitive_int from "rescript/lib/es6/Primitive_int.js";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "rescript/lib/es6/Primitive_exceptions.js";

function Make(funarg) {
  let KEY = Belt_Id.MakeComparableU(funarg);
  let empty = Belt_Map.make(KEY);
  let is_empty = Belt_Map.isEmpty;
  let mem = (elt, b) => Belt_Map.has(b, elt);
  let find = (x, b) => Belt_Map.findFirstBy(b, (k, param) => Primitive_object.equal(k, x));
  let occ = (x, b) => Option.mapOr(find(x, b), 0, param => param[1]);
  let add = (x, multOpt, b) => {
    let mult = multOpt !== undefined ? multOpt : 1;
    if (mult < 0) {
      Pervasives.invalid_arg("add");
    }
    if (mult === 0) {
      return b;
    }
    let m = find(x, b);
    if (m !== undefined) {
      return Belt_Map.set(b, x, m[1] + mult | 0);
    } else {
      return Belt_Map.set(b, x, mult);
    }
  };
  let update = (x, f, b) => {
    let f$1 = o => {
      let m = f(o !== undefined ? o : 0);
      if (m < 0) {
        Pervasives.invalid_arg("update");
      }
      if (m === 0) {
        return;
      } else {
        return m;
      }
    };
    return Belt_Map.update(b, x, f$1);
  };
  let singleton = x => Belt_Map.set(empty, x, 1);
  let remove = (x, multOpt, b) => {
    let mult = multOpt !== undefined ? multOpt : 1;
    if (mult < 0) {
      Pervasives.invalid_arg("remove");
    }
    if (mult === 0) {
      return b;
    } else {
      return Belt_Map.update(b, x, x => {
        if (x !== undefined && x !== 1 && x > mult) {
          return x - mult | 0;
        }
        
      });
    }
  };
  let remove_all = (elt, b) => Belt_Map.remove(b, elt);
  let merge = (f, b1, b2) => {
    let f$1 = (x, o1, o2) => {
      let m1 = o1 !== undefined ? o1 : 0;
      let m2 = o2 !== undefined ? o2 : 0;
      let m = f(x, m1, m2);
      if (m < 0) {
        Pervasives.invalid_arg("merge");
      }
      if (m === 0) {
        return;
      } else {
        return m;
      }
    };
    return Belt_Map.merge(b1, b2, f$1);
  };
  let cardinal = b => Belt_Map.reduce(b, 0, (acc, param, m) => m + acc | 0);
  let elements = Belt_Map.toList;
  let min_elt_opt = b => Option.map(Belt_Map.minKey(b), k => [
    k,
    Belt_Map.getExn(b, k)
  ]);
  let min_elt = b => Option.getExn(min_elt_opt(b), undefined);
  let max_elt_opt = b => Option.map(Belt_Map.maxKey(b), k => [
    k,
    Belt_Map.getExn(b, k)
  ]);
  let max_elt = b => Option.getExn(max_elt_opt(b), undefined);
  let union = (b1, b2) => Belt_Map.merge(b1, b2, (param, o1, o2) => {
    if (o1 === undefined) {
      if (o2 !== undefined) {
        return Primitive_option.some(Primitive_option.valFromOption(o2));
      } else {
        return;
      }
    }
    let m1 = Primitive_option.valFromOption(o1);
    if (o2 !== undefined) {
      return Primitive_option.some(Primitive_object.max(m1, Primitive_option.valFromOption(o2)));
    } else {
      return Primitive_option.some(m1);
    }
  });
  let sum = (b1, b2) => Belt_Map.merge(b1, b2, (param, o1, o2) => {
    if (o1 !== undefined) {
      if (o2 !== undefined) {
        return o1 + o2 | 0;
      } else {
        return o1;
      }
    } else if (o2 !== undefined) {
      return o2;
    } else {
      return;
    }
  });
  let inter = (b1, b2) => Belt_Map.merge(b1, b2, (param, o1, o2) => {
    if (o1 !== undefined && o2 !== undefined) {
      return Primitive_option.some(Primitive_object.min(Primitive_option.valFromOption(o1), Primitive_option.valFromOption(o2)));
    }
    
  });
  let diff = (b1, b2) => Belt_Map.merge(b1, b2, (param, o1, o2) => {
    if (o1 !== undefined) {
      if (o2 !== undefined) {
        if (o1 <= o2) {
          return;
        } else {
          return o1 - o2 | 0;
        }
      } else {
        return o1;
      }
    }
    
  });
  let disjoint = (b1, b2) => Belt_Map.every(b1, (x1, param) => !Belt_Map.has(b2, x1));
  let included = (b1, b2) => Belt_Map.every(b1, (x1, m1) => m1 <= occ(x1, b2));
  let iter = (f, b) => Belt_Map.forEach(b, f);
  let fold = (f, b, acc) => Belt_Map.reduce(b, acc, (acc, k, v) => f(k, v, acc));
  let for_all = (f, b) => Belt_Map.every(b, f);
  let exists = (f, b) => Belt_Map.some(b, f);
  let filter = (f, b) => Belt_Map.keep(b, f);
  let partition = (f, b) => Belt_Map.partition(b, f);
  let split = (x, b) => {
    let match = Belt_Map.split(b, x);
    let m = match[1];
    let match$1 = match[0];
    return [
      match$1[0],
      m !== undefined ? m : 0,
      match$1[1]
    ];
  };
  let find_first_opt = (f, b) => Belt_Map.findFirstBy(b, (k, param) => f(k));
  let find_first = (f, b) => Option.getExn(Belt_Map.findFirstBy(b, (k, param) => f(k)), undefined);
  let map = (f, b) => {
    let f$1 = m => {
      let m$1 = f(m);
      if (m$1 <= 0) {
        Pervasives.invalid_arg("map");
      }
      return m$1;
    };
    return Belt_Map.map(b, f$1);
  };
  let mapi = (f, b) => {
    let f$1 = (x, m) => {
      let m$1 = f(x, m);
      if (m$1 <= 0) {
        Pervasives.invalid_arg("mapi");
      }
      return m$1;
    };
    return Belt_Map.mapWithKey(b, f$1);
  };
  let mul = (b, n) => {
    if (n < 0) {
      Pervasives.invalid_arg("mul");
    }
    if (n === 0) {
      return empty;
    } else {
      return map(m => Math.imul(m, n), b);
    }
  };
  let div = (b1, b2) => {
    if (Belt_Map.isEmpty(b2)) {
      return [
        0,
        b1
      ];
    }
    try {
      let update = (x, m1, q) => {
        let m2 = occ(x, b2);
        if (m2 === 0 || m2 > m1) {
          throw {
            RE_EXN_ID: Pervasives.Exit,
            Error: new Error()
          };
        }
        return Primitive_int.min(q, Primitive_int.div(m1, m2));
      };
      let q = fold(update, b1, Pervasives.max_int);
      if (q <= 0) {
        throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "bag.res",
            274,
            8
          ],
          Error: new Error()
        };
      }
      let remainder = (x, m1, r) => {
        let mult = m1 - Math.imul(q, occ(x, b2)) | 0;
        return add(x, mult, r);
      };
      let r = fold(remainder, b1, empty);
      return [
        q,
        r
      ];
    } catch (raw_exn) {
      let exn = Primitive_exceptions.internalToException(raw_exn);
      if (exn.RE_EXN_ID === Pervasives.Exit) {
        return [
          0,
          b1
        ];
      }
      throw exn;
    }
  };
  let divi = (b, n) => {
    if (n <= 0) {
      Pervasives.invalid_arg("divi");
    }
    let update = (x, m, param) => [
      add(x, Primitive_int.div(m, n), param[0]),
      add(x, Primitive_int.mod_(m, n), param[1])
    ];
    return fold(update, b, [
      empty,
      empty
    ]);
  };
  let compare = (b1, b2) => Belt_Map.cmp(b1, b2, (v1, v2) => v2 - v1 | 0);
  let equal = (b1, b2) => Belt_Map.eq(b1, b2, Primitive_object.equal);
  return {
    empty: empty,
    is_empty: is_empty,
    occ: occ,
    mem: mem,
    add: add,
    update: update,
    singleton: singleton,
    remove: remove,
    remove_all: remove_all,
    merge: merge,
    cardinal: cardinal,
    elements: elements,
    min_elt: min_elt,
    min_elt_opt: min_elt_opt,
    max_elt: max_elt,
    max_elt_opt: max_elt_opt,
    union: union,
    sum: sum,
    mul: mul,
    div: div,
    divi: divi,
    inter: inter,
    diff: diff,
    disjoint: disjoint,
    included: included,
    iter: iter,
    fold: fold,
    for_all: for_all,
    exists: exists,
    filter: filter,
    partition: partition,
    split: split,
    find_first: find_first,
    find_first_opt: find_first_opt,
    map: map,
    mapi: mapi,
    compare: compare,
    equal: equal
  };
}

export {
  Make,
}
/* No side effect */
